In [1]:
import pandas as pd

In [2]:
Housing_2021="Resources/2021PhilaHousing.csv"
Housing_2019="Resources/2019PhilaHousing.csv"
Housing_2018="Resources/2018PhilaHousing.csv"
Housing_2017="Resources/2017PhilaHousing.csv"
Housing_2016="Resources/2016PhilaHousing.csv"
Housing_2015="Resources/2015PhilaHousing.csv"
Housing_2014="Resources/2014PhilaHousing.csv"
Housing_2013="Resources/2013PhilaHousing.csv"
Housing_2012="Resources/2012PhilaHousing.csv"
Housing_2011="Resources/2011PhilaHousing.csv"
Housing_2010="Resources/2010PhilaHousing.csv"

In [3]:
housing_21=pd.read_csv(Housing_2021)
housing_19=pd.read_csv(Housing_2019)
housing_18=pd.read_csv(Housing_2018)
housing_17=pd.read_csv(Housing_2017)
housing_16=pd.read_csv(Housing_2016)
housing_15=pd.read_csv(Housing_2015)
housing_14=pd.read_csv(Housing_2014)
housing_13=pd.read_csv(Housing_2013)
housing_12=pd.read_csv(Housing_2012)
housing_11=pd.read_csv(Housing_2011)
housing_10=pd.read_csv(Housing_2010)
housing_19

,Label (Grouping),"Philadelphia city, Pennsylvania!!Estimate","Philadelphia city, Pennsylvania!!Margin of Error","Philadelphia city, Pennsylvania!!Percent","Philadelphia city, Pennsylvania!!Percent Margin of Error"
0,HOUSING OCCUPANCY,NaN,NaN,NaN,NaN
1,Total housing units,"691,653","±1,639","691,653",(X)
2,Occupied housing units,"619,505","±4,709",89.6%,±0.6
3,Vacant housing units,"72,148","±4,430",10.4%,±0.6
4,Homeowner vacancy rate,1.1,±0.4,(X),(X)
...,...,...,...,...,...
155,20.0 to 24.9 percent,"30,663","±3,127",10.9%,±1.1
156,25.0 to 29.9 percent,"31,283","±3,747",11.2%,±1.3
157,30.0 to 34.9 percent,"26,138","±3,397",9.3%,±1.2
158,35.0 percent or more,"127,253","±6,657",45.4%,±2.0
159,Not computed,"15,561","±2,407",(X),(X)

Isolate Occupancy Data

In [4]:
Occupancy21=housing_21.iloc[1:15]
Occupancy19=housing_19.iloc[1:15]
Occupancy18=housing_18.iloc[1:15]
Occupancy17=housing_17.iloc[1:15]
Occupancy16=housing_16.iloc[1:15]
Occupancy15=housing_15.iloc[1:15]
Occupancy14=housing_14.iloc[1:15]
Occupancy13=housing_13.iloc[1:15]
Occupancy12=housing_12.iloc[1:15]
Occupancy11=housing_11.iloc[1:15]
Occupancy10=housing_10.iloc[1:15]
O21=Occupancy21.drop(['Philadelphia city, Pennsylvania!!Margin of Error', 'Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
O19=Occupancy19.drop(['Philadelphia city, Pennsylvania!!Margin of Error', 'Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
O18=Occupancy18.drop(['Philadelphia city, Pennsylvania!!Margin of Error', 'Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
O17=Occupancy17.drop(['Philadelphia city, Pennsylvania!!Margin of Error', 'Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
O16=Occupancy16.drop(['Philadelphia city, Pennsylvania!!Margin of Error', 'Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)

Isolate Gross Rent Data

In [5]:
GrossRent21=housing_21.iloc[140:161]
GrossRent19=housing_19.iloc[140:161]
GrossRent18=housing_18.iloc[140:161]
GrossRent17=housing_17.iloc[140:161]
GrossRent16=housing_16.iloc[140:161]
GrossRent15=housing_15.iloc[140:161]
GrossRent14=housing_14.iloc[140:161]
GrossRent13=housing_13.iloc[140:161]
GrossRent12=housing_12.iloc[140:161]
GrossRent11=housing_11.iloc[140:161]
GrossRent10=housing_10.iloc[140:161]
GR21=GrossRent21.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR19=GrossRent19.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR18=GrossRent18.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR17=GrossRent17.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR16=GrossRent16.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR15=GrossRent15.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR14=GrossRent14.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR13=GrossRent13.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR12=GrossRent12.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR11=GrossRent11.drop(['Philadelphia city, Pennsylvania!!Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR10=GrossRent10.drop(['Philadelphia city, Pennsylvania!!Estimate Margin of Error','Philadelphia city, Pennsylvania!!Percent Margin of Error'], axis=1)
GR10

,Label (Grouping),"Philadelphia city, Pennsylvania!!Estimate","Philadelphia city, Pennsylvania!!Percent"
140,Less than $200,"8,846",3.5%
141,$200 to $299,"11,550",4.6%
142,$300 to $499,"21,357",8.5%
143,$500 to $749,"53,055",21.1%
144,$750 to $999,"73,877",29.4%
145,"$1,000 to $1,499","60,172",24.0%
146,"$1,500 or more","22,212",8.8%
147,Median (dollars),836,(X)
148,No rent paid,"13,060",(X)
149,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,NaN,NaN
150,Occupied units paying rent (excluding unit...,"238,432","238,432"
151,Less than 15.0 percent,"20,374",8.5%
152,15.0 to 19.9 percent,"26,471",11.1%
153,20.0 to 24.9 percent,"25,494",10.7%
154,25.0 to 29.9 percent,"25,721",10.8%
155,30.0 to 34.9 percent,"20,434",8.6%
156,35.0 percent or more,"119,938",50.3%
157,Not computed,"25,697",(X)

Merge Chain GR:

In [22]:
GR21=GR21.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2021','Philadelphia city, Pennsylvania!!Percent':'2021 Percent' }, axis='columns')
GR19=GR19.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2019','Philadelphia city, Pennsylvania!!Percent':'2019 Percent' }, axis='columns')
GR18=GR18.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2018','Philadelphia city, Pennsylvania!!Percent':'2018 Percent' }, axis='columns')
GR17=GR17.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2017','Philadelphia city, Pennsylvania!!Percent':'2017 Percent' }, axis='columns')
GR16=GR16.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2016','Philadelphia city, Pennsylvania!!Percent':'2016 Percent' }, axis='columns')
GR15=GR15.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2015','Philadelphia city, Pennsylvania!!Percent':'2015 Percent' }, axis='columns')
GR14=GR14.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2014','Philadelphia city, Pennsylvania!!Percent':'2014 Percent' }, axis='columns')
GR13=GR13.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2013','Philadelphia city, Pennsylvania!!Percent':'2013 Percent' }, axis='columns')
GR12=GR12.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2012','Philadelphia city, Pennsylvania!!Percent':'2012 Percent' }, axis='columns')
GR11=GR11.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2011','Philadelphia city, Pennsylvania!!Percent':'2011 Percent' }, axis='columns')
GR10=GR10.rename({'Philadelphia city, Pennsylvania!!Estimate':'Census Estimate 2010','Philadelphia city, Pennsylvania!!Percent':'2010 Percent' }, axis='columns')

GR_Data = [GR10,GR11,GR12,GR13,GR14,GR15,GR16,GR17,GR18,GR19,GR21]
def strip_strings(s):
    return s.strip()

for inx, GR in enumerate(GR_Data):
    year = 2010 + inx
    if year == 2020:
        year = 2021
    #Changes Column names
    GR=GR.rename({'Philadelphia city, Pennsylvania!!Estimate':f'Census Estimate {year}',
                            'Philadelphia city, Pennsylvania!!Percent':f'{year} Percent' }, axis='columns')
    # Fixes Label strings
    GR = GR['Label (Grouping)'].apply(strip_strings)
    GR_Data[inx] = GR

140                                           GROSS RENT
141                           Occupied units paying rent
142                                       Less than $500
143                                         $500 to $999
144                                     $1,000 to $1,499
145                                     $1,500 to $1,999
146                                     $2,000 to $2,499
147                                     $2,500 to $2,999
148                                       $3,000 or more
149                                     Median (dollars)
150                                         No rent paid
151    GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...
152    Occupied units paying rent (excluding units wh...
153                               Less than 15.0 percent
154                                 15.0 to 19.9 percent
155                                 20.0 to 24.9 percent
156                                 25.0 to 29.9 percent
157                                 30.0 to 34.9 percent
158                                 35.0 percent or more
159                                         Not computed
Name: Label (Grouping), dtype: object

In [11]:
#initial_gr = GR_Data[0]

#for GR in GR_Data[1:]:
        #GR=initial_GR.merge(GR+f', how='left', on='Label (Grouping)')
        
#merge=GR10.merge(GR11, how='left', on='Label (Grouping)')
#merge=merge.merge(GR12, how='left', on='Label (Grouping)')
#merge=merge.merge(GR13, how='left', on='Label (Grouping)')
#merge=merge.merge(GR14, how='left', on='Label (Grouping)')
#merge=merge.merge(GR15, how='left', on='Label (Grouping)')
#merge=merge.merge(GR16, how='left', on='Label (Grouping)')
#merge=merge.merge(GR17, how='left', on='Label (Grouping)')
#merge=merge.merge(GR18, how='left', on='Label (Grouping)')
#merge=merge.merge(GR19, how='left', on='Label (Grouping)')
#merge=merge.merge(GR21, how='left', on='Label (Grouping)')
#merge

,Label (Grouping),Census Estimate 2010,2010 Percent,Census Estimate 2011,2011 Percent,Census Estimate 2012,2012 Percent,Census Estimate 2013,2013 Percent,Census Estimate 2014,...,Census Estimate 2016,2016 Percent,Census Estimate 2017,2017 Percent,Census Estimate 2018,2018 Percent,Census Estimate 2019,2019 Percent,Census Estimate 2021,2021 Percent
0,Less than $200,"8,846",3.5%,"8,576",3.4%,"9,639",3.6%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,$200 to $299,"11,550",4.6%,"10,015",4.0%,"9,561",3.6%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,$300 to $499,"21,357",8.5%,"19,931",7.9%,"19,077",7.2%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,$500 to $749,"53,055",21.1%,"54,157",21.4%,"53,698",20.2%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,$750 to $999,"73,877",29.4%,"77,931",30.8%,"79,820",30.1%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"$1,000 to $1,499","60,172",24.0%,"60,453",23.9%,"67,868",25.6%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"$1,500 or more","22,212",8.8%,"22,162",8.8%,"25,925",9.8%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Median (dollars),836,(X),853,(X),876,(X),NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,No rent paid,"13,060",(X),"11,901",(X),"11,735",(X),"13,450",(X),"12,008",...,"10,523",(X),"23,087",(X),NaN,NaN,NaN,NaN,NaN,NaN
9,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Occupied units paying rent (excluding unit...,"238,432","238,432","242,853","242,853","252,747","252,747","259,041","259,041","254,585",...,"250,113","250,113","246,758","246,758","264,075","264,075","280,222","280,222","290,133","290,133"
11,Less than 15.0 percent,"20,374",8.5%,"21,575",8.9%,"24,791",9.8%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,15.0 to 19.9 percent,"26,471",11.1%,"22,195",9.1%,"25,719",10.2%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,20.0 to 24.9 percent,"25,494",10.7%,"27,797",11.4%,"29,180",11.5%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,25.0 to 29.9 percent,"25,721",10.8%,"30,134",12.4%,"29,151",11.5%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,30.0 to 34.9 percent,"20,434",8.6%,"17,157",7.1%,"22,205",8.8%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,35.0 percent or more,"119,938",50.3%,"123,995",51.1%,"121,701",48.2%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Not computed,"25,697",(X),"22,273",(X),"24,576",(X),"26,389",(X),"22,716",...,"27,594",(X),"62,521",(X),NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(GR12.columns)
print(GR13.columns)

In [ ]:
print(all(GR12['Label (Grouping)'] == GR13['Label (Grouping)']))
def strip_strings(s):
    return s.strip()
print(all(GR12['Label (Grouping)'].apply(strip_strings) == GR13['Label (Grouping)'].apply(strip_strings)))